// <auto-generated />
using System;
using Bitacora_API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bitacora_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901210141_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutorObra", b =>
                {
                    b.Property<Guid>("AutoresId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObrasId")
                        .HasColumnType("uuid");

                    b.HasKey("AutoresId", "ObrasId");

                    b.HasIndex("ObrasId");

                    b.ToTable("AutorObra");
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Autor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Biografia")
                        .HasColumnType("text")
                        .HasColumnName("biografia");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("autores", (string)null);
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Biblioteca", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EdicionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaAgregado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_agregado")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UsuarioId", "EdicionId");

                    b.HasIndex("EdicionId");

                    b.ToTable("bibliotecas", (string)null);
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Edicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio_publicacion");

                    b.Property<string>("Editorial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("editorial");

                    b.Property<int>("Formato")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("formato");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("isbn");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid")
                        .HasColumnName("obra_id");

                    b.Property<int?>("Paginas")
                        .HasColumnType("integer")
                        .HasColumnName("numero_paginas");

                    b.Property<string>("PortadaURL")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("portada_url");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<int?>("duracionMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_minutos");

                    b.HasKey("Id");

                    b.HasIndex("Isbn")
                        .IsUnique()
                        .HasFilter("isbn IS NOT NULL");

                    b.HasIndex("ObraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ediciones", (string)null);
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.EntradaBitacora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("LecturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("lectura_id");

                    b.Property<Guid>("SesionLecturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesio_lectura_id");

                    b.Property<bool>("Spoilers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("contiene_spoilers");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("LecturaId");

                    b.HasIndex("SesionLecturaId");

                    b.ToTable("entradas_bitacora", (string)null);
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Genero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("generos", (string)null);
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Lectura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EdicionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edicion_id");

                    b.Property<int>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("NumeroRelecturas")
                        .HasColumnType("integer")
                        .HasColumnName("numero_relecturas");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("EdicionId");

                    b.HasIndex("UsuarioId", "EdicionId", "NumeroRelecturas")
                        .IsUnique();

                    b.ToTable("lecturas", (string)null);
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Obra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("sinopsis");

                    b.Property<DateOnly?>("Publicacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_publicacion");

                    b.Property<Guid?>("SagaId")
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.Property<string>("TipoObra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_obra");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("titulo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SagaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("obras", (string)null);
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.ObraAutor", b =>
                {
                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.HasKey("ObraId", "AutorId");

                    b.HasIndex("AutorId");

                    b.ToTable("obra_autor", (string)null);
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.ObraGenero", b =>
                {
                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GeneroId")
                        .HasColumnType("uuid");

                    b.HasKey("ObraId", "GeneroId");

                    b.HasIndex("GeneroId");

                    b.ToTable("obra_genero", (string)null);
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Saga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("sagas", (string)null);
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.SesionLectura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<Guid>("LecturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("lectura_id");

                    b.Property<int?>("Minutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_minutos");

                    b.Property<decimal>("Progreso")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("progreso");

                    b.HasKey("Id");

                    b.HasIndex("LecturaId", "Fecha");

                    b.ToTable("sesiones_lectura", (string)null);
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contrasena_hasheada");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Valoracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("LecturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("lectura_id");

                    b.Property<int>("Puntuacion")
                        .HasPrecision(2, 1)
                        .HasColumnType("integer")
                        .HasColumnName("puntuacion");

                    b.Property<string>("Resena")
                        .HasColumnType("text")
                        .HasColumnName("resena");

                    b.HasKey("Id");

                    b.HasIndex("LecturaId")
                        .IsUnique();

                    b.ToTable("valoraciones", null, t =>
                        {
                            t.HasCheckConstraint("ck_valoracion_puntuacion", "puntuacion >= 0 AND puntuacion <= 5");
                        });
                });

            modelBuilder.Entity("GeneroObra", b =>
                {
                    b.Property<Guid>("GenerosId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObrasId")
                        .HasColumnType("uuid");

                    b.HasKey("GenerosId", "ObrasId");

                    b.HasIndex("ObrasId");

                    b.ToTable("GeneroObra");
                });

            modelBuilder.Entity("AutorObra", b =>
                {
                    b.HasOne("Bitacora_API.Domain.Entities.Autor", null)
                        .WithMany()
                        .HasForeignKey("AutoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bitacora_API.Domain.Entities.Obra", null)
                        .WithMany()
                        .HasForeignKey("ObrasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Autor", b =>
                {
                    b.HasOne("Bitacora_API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Autores")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Biblioteca", b =>
                {
                    b.HasOne("Bitacora_API.Domain.Entities.Edicion", "Edicion")
                        .WithMany("Bibliotecas")
                        .HasForeignKey("EdicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bitacora_API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Bibliotecas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edicion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Edicion", b =>
                {
                    b.HasOne("Bitacora_API.Domain.Entities.Obra", "Obra")
                        .WithMany("Ediciones")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bitacora_API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Ediciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.EntradaBitacora", b =>
                {
                    b.HasOne("Bitacora_API.Domain.Entities.Lectura", "Lectura")
                        .WithMany("Entradas")
                        .HasForeignKey("LecturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bitacora_API.Domain.Entities.SesionLectura", "SesionLectura")
                        .WithMany("Entradas")
                        .HasForeignKey("SesionLecturaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Lectura");

                    b.Navigation("SesionLectura");
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Lectura", b =>
                {
                    b.HasOne("Bitacora_API.Domain.Entities.Edicion", "Edicion")
                        .WithMany("Lecturas")
                        .HasForeignKey("EdicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bitacora_API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Lecturas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edicion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Obra", b =>
                {
                    b.HasOne("Bitacora_API.Domain.Entities.Saga", "Saga")
                        .WithMany("Obras")
                        .HasForeignKey("SagaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bitacora_API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Obras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Saga");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.ObraAutor", b =>
                {
                    b.HasOne("Bitacora_API.Domain.Entities.Autor", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bitacora_API.Domain.Entities.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.ObraGenero", b =>
                {
                    b.HasOne("Bitacora_API.Domain.Entities.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bitacora_API.Domain.Entities.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Saga", b =>
                {
                    b.HasOne("Bitacora_API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Sagas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.SesionLectura", b =>
                {
                    b.HasOne("Bitacora_API.Domain.Entities.Lectura", "Lectura")
                        .WithMany("Sesiones")
                        .HasForeignKey("LecturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lectura");
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Valoracion", b =>
                {
                    b.HasOne("Bitacora_API.Domain.Entities.Lectura", "Lectura")
                        .WithOne("Valoracion")
                        .HasForeignKey("Bitacora_API.Domain.Entities.Valoracion", "LecturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lectura");
                });

            modelBuilder.Entity("GeneroObra", b =>
                {
                    b.HasOne("Bitacora_API.Domain.Entities.Genero", null)
                        .WithMany()
                        .HasForeignKey("GenerosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bitacora_API.Domain.Entities.Obra", null)
                        .WithMany()
                        .HasForeignKey("ObrasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Edicion", b =>
                {
                    b.Navigation("Bibliotecas");

                    b.Navigation("Lecturas");
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Lectura", b =>
                {
                    b.Navigation("Entradas");

                    b.Navigation("Sesiones");

                    b.Navigation("Valoracion");
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Obra", b =>
                {
                    b.Navigation("Ediciones");
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Saga", b =>
                {
                    b.Navigation("Obras");
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.SesionLectura", b =>
                {
                    b.Navigation("Entradas");
                });

            modelBuilder.Entity("Bitacora_API.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Autores");

                    b.Navigation("Bibliotecas");

                    b.Navigation("Ediciones");

                    b.Navigation("Lecturas");

                    b.Navigation("Obras");

                    b.Navigation("Sagas");
                });
#pragma warning restore 612, 618
        }
    }
}
